### ISSUE TITLE
Bug: Reconnection is not working with mongoose

### ISSUE THREAD

**Issue by titanism** [typegoose/mongodb-memory-server#739]
Out of the box, it appears reconnection is not working with MongoDB memory server and Mongoose.

See failed test and example here: <https://github.com/Automattic/mongoose/issues/12961>.

Posting here as well as in the Mongoose thread for discussion.

**Comment by hasezoey** [comment]
MMS does not change anything on how mongodb works, the only thing to note is that `sever.stop()` automatically cleans-up the files it had created unless disabled or a manually set db-path is used, see [`MongoMemoryServer.stop`](https://nodkz.github.io/mongodb-memory-server/docs/api/classes/mongo-memory-server#stop).

> Stop an running instance, this function will by default call [.cleanup](https://nodkz.github.io/mongodb-memory-server/docs/api/classes/mongo-memory-server#cleanup) with { doCleanup: true, force: false }.

and after a clean-up a instance might use a different port and so mongoose may not be able to re-connect on the same URI.

if you dont want cleanup:
```ts
const server = await MongoMemoryServer.create();
await server.stop({ doCleanup: false });
await server.start(true); // will be the same instance again

await server.stop(); // to finally clean-up again
```

also note that not adding `true` to `.start` might still make the instance use a different port if the previous port got unavailable in the meantime.

---

those are the defaults because that is how MMS is most commonly used (and expected to run).
cleanup is done by default when using auto-generated directory, because most commonly a db-path (not using `ephermeralForTest`) can quickly shoot up to 500mb with not many documents inside and can often be easily forgot to manually call `.cleanup`.
